[package]
name = "calibrator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha256 = "1.0.2"
rand = "0.8.3"
structopt = "0.3.21"
itertools = "0.10.1"